import type { InferGetStaticPropsType, NextPage } from "next";
import Head from "next/head";
import Link from 'next/link'
import styles from "~/styles/Home.module.css";
import { getAllPosts } from "~/lib/getContentIndex";
import PageTitle from "~/components/common/pageTitle";

type Props = InferGetStaticPropsType<typeof getStaticProps>;

export const getStaticProps = async () => {
    const allPosts = getAllPosts(["slug", "title", "date", "tags"]);
    return {
        props: { allPosts },
    };
};

const Home: NextPage<Props> = ({ allPosts }) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>rhiroeのブログ</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <PageTitle>rhiroeのブログ</PageTitle>

                <div>
                    {allPosts.map((post) => (
                        <Link href={`blog/${post.slug}`} key={post.slug}>
                            <a>
                                <h2>{post.title}</h2>
                                <p>{post.date}</p>
                            </a>
                        </Link>
                    ))}
                </div>
            </main>
        </div>
    );
};

export default Home;
