name: Run ESLint

# 必要最小限の権限設定
permissions:
  contents: read  # リポジトリ内容の読み取りのみ

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run eslint
        run: npm run lint
