name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  ESLint:
    uses: ./.github/workflows/eslint.yml

  Test:
    uses: ./.github/workflows/test.yml

  Deploy:
    needs:
      - ESLint
      - Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: export
        run: yarn export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
