name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  ESLint:
    uses: ./.github/workflows/eslint.yml

  Test:
    uses: ./.github/workflows/test.yml

  Build:
    needs:
      - ESLint
      - Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: corepack enable
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build
        env:
          NEXT_PUBLIC_GITHUB_TOKEN: ${{ secrets.NEXT_PUBLIC_GITHUB_TOKEN }}

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  Deploy:
    needs: Build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
